# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'gui_work2.ui'
##
## Created by: Qt User Interface Compiler version 6.9.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QFrame, QGroupBox,
    QHeaderView, QLabel, QMainWindow, QMenu,
    QMenuBar, QProgressBar, QPushButton, QSizePolicy,
    QStatusBar, QTabWidget, QTableWidget, QTableWidgetItem,
    QTextEdit, QWidget)

from pyqtgraph import PlotWidget

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(791, 598)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.tabWidget = QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setGeometry(QRect(0, 0, 791, 551))
        self.tabWidget.setLocale(QLocale(QLocale.English, QLocale.UnitedStates))
        self.tab = QWidget()
        self.tab.setObjectName(u"tab")
        self.tabWidget_2 = QTabWidget(self.tab)
        self.tabWidget_2.setObjectName(u"tabWidget_2")
        self.tabWidget_2.setGeometry(QRect(180, 30, 581, 351))
        self.tab_6 = QWidget()
        self.tab_6.setObjectName(u"tab_6")
        self.tableWidget = QTableWidget(self.tab_6)
        if (self.tableWidget.columnCount() < 5):
            self.tableWidget.setColumnCount(5)
        __qtablewidgetitem = QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, __qtablewidgetitem)
        __qtablewidgetitem1 = QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, __qtablewidgetitem1)
        __qtablewidgetitem2 = QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, __qtablewidgetitem2)
        __qtablewidgetitem3 = QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, __qtablewidgetitem3)
        __qtablewidgetitem4 = QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, __qtablewidgetitem4)
        self.tableWidget.setObjectName(u"tableWidget")
        self.tableWidget.setGeometry(QRect(60, 50, 501, 211))
        self.pushButton_2 = QPushButton(self.tab_6)
        self.pushButton_2.setObjectName(u"pushButton_2")
        self.pushButton_2.setGeometry(QRect(60, 270, 101, 41))
        self.pushButton_3 = QPushButton(self.tab_6)
        self.pushButton_3.setObjectName(u"pushButton_3")
        self.pushButton_3.setGeometry(QRect(170, 270, 101, 41))
        self.label = QLabel(self.tab_6)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(60, 10, 711, 21))
        font = QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.tabWidget_2.addTab(self.tab_6, "")
        self.tab_7 = QWidget()
        self.tab_7.setObjectName(u"tab_7")
        self.tableWidget_3 = QTableWidget(self.tab_7)
        if (self.tableWidget_3.columnCount() < 5):
            self.tableWidget_3.setColumnCount(5)
        __qtablewidgetitem5 = QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(0, __qtablewidgetitem5)
        __qtablewidgetitem6 = QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(1, __qtablewidgetitem6)
        __qtablewidgetitem7 = QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(2, __qtablewidgetitem7)
        __qtablewidgetitem8 = QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(3, __qtablewidgetitem8)
        __qtablewidgetitem9 = QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(4, __qtablewidgetitem9)
        self.tableWidget_3.setObjectName(u"tableWidget_3")
        self.tableWidget_3.setGeometry(QRect(60, 50, 501, 211))
        self.pushButton_7 = QPushButton(self.tab_7)
        self.pushButton_7.setObjectName(u"pushButton_7")
        self.pushButton_7.setGeometry(QRect(60, 270, 101, 41))
        self.pushButton_6 = QPushButton(self.tab_7)
        self.pushButton_6.setObjectName(u"pushButton_6")
        self.pushButton_6.setGeometry(QRect(170, 270, 101, 41))
        self.label_2 = QLabel(self.tab_7)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(60, 10, 711, 21))
        self.label_2.setFont(font)
        self.tabWidget_2.addTab(self.tab_7, "")
        self.Mansoon = QWidget()
        self.Mansoon.setObjectName(u"Mansoon")
        self.tableWidget_4 = QTableWidget(self.Mansoon)
        if (self.tableWidget_4.columnCount() < 5):
            self.tableWidget_4.setColumnCount(5)
        __qtablewidgetitem10 = QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(0, __qtablewidgetitem10)
        __qtablewidgetitem11 = QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(1, __qtablewidgetitem11)
        __qtablewidgetitem12 = QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(2, __qtablewidgetitem12)
        __qtablewidgetitem13 = QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(3, __qtablewidgetitem13)
        __qtablewidgetitem14 = QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(4, __qtablewidgetitem14)
        self.tableWidget_4.setObjectName(u"tableWidget_4")
        self.tableWidget_4.setGeometry(QRect(60, 50, 501, 211))
        self.pushButton_8 = QPushButton(self.Mansoon)
        self.pushButton_8.setObjectName(u"pushButton_8")
        self.pushButton_8.setGeometry(QRect(170, 270, 101, 41))
        self.pushButton_9 = QPushButton(self.Mansoon)
        self.pushButton_9.setObjectName(u"pushButton_9")
        self.pushButton_9.setGeometry(QRect(60, 270, 101, 41))
        self.label_3 = QLabel(self.Mansoon)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(60, 10, 711, 21))
        self.label_3.setFont(font)
        self.tabWidget_2.addTab(self.Mansoon, "")
        self.tab_10 = QWidget()
        self.tab_10.setObjectName(u"tab_10")
        self.tableWidget_5 = QTableWidget(self.tab_10)
        if (self.tableWidget_5.columnCount() < 5):
            self.tableWidget_5.setColumnCount(5)
        __qtablewidgetitem15 = QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(0, __qtablewidgetitem15)
        __qtablewidgetitem16 = QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(1, __qtablewidgetitem16)
        __qtablewidgetitem17 = QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(2, __qtablewidgetitem17)
        __qtablewidgetitem18 = QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(3, __qtablewidgetitem18)
        __qtablewidgetitem19 = QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(4, __qtablewidgetitem19)
        self.tableWidget_5.setObjectName(u"tableWidget_5")
        self.tableWidget_5.setGeometry(QRect(60, 50, 501, 211))
        self.pushButton_11 = QPushButton(self.tab_10)
        self.pushButton_11.setObjectName(u"pushButton_11")
        self.pushButton_11.setGeometry(QRect(60, 270, 101, 41))
        self.pushButton_10 = QPushButton(self.tab_10)
        self.pushButton_10.setObjectName(u"pushButton_10")
        self.pushButton_10.setGeometry(QRect(170, 270, 101, 41))
        self.label_4 = QLabel(self.tab_10)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(60, 10, 711, 21))
        self.label_4.setFont(font)
        self.tabWidget_2.addTab(self.tab_10, "")
        self.pushButton = QPushButton(self.tab)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setGeometry(QRect(180, 390, 181, 24))
        self.groupBox_4 = QGroupBox(self.tab)
        self.groupBox_4.setObjectName(u"groupBox_4")
        self.groupBox_4.setGeometry(QRect(10, 80, 161, 271))
        self.label_19 = QLabel(self.groupBox_4)
        self.label_19.setObjectName(u"label_19")
        self.label_19.setGeometry(QRect(30, 50, 101, 16))
        self.textEdit_15 = QTextEdit(self.groupBox_4)
        self.textEdit_15.setObjectName(u"textEdit_15")
        self.textEdit_15.setGeometry(QRect(30, 70, 104, 21))
        self.label_20 = QLabel(self.groupBox_4)
        self.label_20.setObjectName(u"label_20")
        self.label_20.setGeometry(QRect(30, 130, 101, 16))
        self.textEdit_16 = QTextEdit(self.groupBox_4)
        self.textEdit_16.setObjectName(u"textEdit_16")
        self.textEdit_16.setGeometry(QRect(30, 150, 104, 21))
        self.textEdit_17 = QTextEdit(self.groupBox_4)
        self.textEdit_17.setObjectName(u"textEdit_17")
        self.textEdit_17.setGeometry(QRect(30, 230, 104, 21))
        self.label_21 = QLabel(self.groupBox_4)
        self.label_21.setObjectName(u"label_21")
        self.label_21.setGeometry(QRect(30, 210, 101, 16))
        self.textEdit_31 = QTextEdit(self.tab)
        self.textEdit_31.setObjectName(u"textEdit_31")
        self.textEdit_31.setGeometry(QRect(160, 477, 591, 21))
        self.pushButton_18 = QPushButton(self.tab)
        self.pushButton_18.setObjectName(u"pushButton_18")
        self.pushButton_18.setGeometry(QRect(50, 470, 101, 31))
        self.label_53 = QLabel(self.tab)
        self.label_53.setObjectName(u"label_53")
        self.label_53.setGeometry(QRect(50, 440, 561, 16))
        self.tabWidget.addTab(self.tab, "")
        self.tab_3 = QWidget()
        self.tab_3.setObjectName(u"tab_3")
        self.checkBox = QCheckBox(self.tab_3)
        self.checkBox.setObjectName(u"checkBox")
        self.checkBox.setGeometry(QRect(70, 140, 151, 20))
        self.checkBox_2 = QCheckBox(self.tab_3)
        self.checkBox_2.setObjectName(u"checkBox_2")
        self.checkBox_2.setGeometry(QRect(70, 160, 141, 20))
        self.checkBox_3 = QCheckBox(self.tab_3)
        self.checkBox_3.setObjectName(u"checkBox_3")
        self.checkBox_3.setGeometry(QRect(70, 180, 191, 20))
        self.checkBox_4 = QCheckBox(self.tab_3)
        self.checkBox_4.setObjectName(u"checkBox_4")
        self.checkBox_4.setGeometry(QRect(70, 200, 201, 20))
        self.checkBox_5 = QCheckBox(self.tab_3)
        self.checkBox_5.setObjectName(u"checkBox_5")
        self.checkBox_5.setGeometry(QRect(70, 220, 171, 20))
        self.groupBox_5 = QGroupBox(self.tab_3)
        self.groupBox_5.setObjectName(u"groupBox_5")
        self.groupBox_5.setGeometry(QRect(30, 40, 291, 231))
        self.line = QFrame(self.groupBox_5)
        self.line.setObjectName(u"line")
        self.line.setGeometry(QRect(20, 70, 251, 16))
        self.line.setFrameShape(QFrame.Shape.HLine)
        self.line.setFrameShadow(QFrame.Shadow.Sunken)
        self.label_22 = QLabel(self.groupBox_5)
        self.label_22.setObjectName(u"label_22")
        self.label_22.setGeometry(QRect(20, 20, 261, 31))
        self.label_23 = QLabel(self.groupBox_5)
        self.label_23.setObjectName(u"label_23")
        self.label_23.setGeometry(QRect(20, 50, 281, 16))
        self.groupBox_6 = QGroupBox(self.groupBox_5)
        self.groupBox_6.setObjectName(u"groupBox_6")
        self.groupBox_6.setGeometry(QRect(20, 230, 291, 231))
        self.line_2 = QFrame(self.groupBox_6)
        self.line_2.setObjectName(u"line_2")
        self.line_2.setGeometry(QRect(20, 70, 251, 16))
        self.line_2.setFrameShape(QFrame.Shape.HLine)
        self.line_2.setFrameShadow(QFrame.Shadow.Sunken)
        self.label_24 = QLabel(self.groupBox_6)
        self.label_24.setObjectName(u"label_24")
        self.label_24.setGeometry(QRect(20, 20, 261, 31))
        self.label_25 = QLabel(self.groupBox_6)
        self.label_25.setObjectName(u"label_25")
        self.label_25.setGeometry(QRect(20, 50, 281, 16))
        self.pushButton_4 = QPushButton(self.tab_3)
        self.pushButton_4.setObjectName(u"pushButton_4")
        self.pushButton_4.setGeometry(QRect(20, 450, 121, 41))
        font1 = QFont()
        font1.setKerning(True)
        self.pushButton_4.setFont(font1)
        self.pushButton_4.setAutoFillBackground(True)
        self.progressBar = QProgressBar(self.tab_3)
        self.progressBar.setObjectName(u"progressBar")
        self.progressBar.setGeometry(QRect(170, 460, 591, 23))
        self.progressBar.setValue(24)
        self.GrapWidget = QWidget(self.tab_3)
        self.GrapWidget.setObjectName(u"GrapWidget")
        self.GrapWidget.setGeometry(QRect(350, 50, 411, 371))
        self.groupBox_7 = QGroupBox(self.tab_3)
        self.groupBox_7.setObjectName(u"groupBox_7")
        self.groupBox_7.setGeometry(QRect(30, 300, 291, 91))
        self.label_26 = QLabel(self.groupBox_7)
        self.label_26.setObjectName(u"label_26")
        self.label_26.setGeometry(QRect(10, 30, 191, 16))
        self.label_27 = QLabel(self.groupBox_7)
        self.label_27.setObjectName(u"label_27")
        self.label_27.setGeometry(QRect(10, 60, 191, 16))
        self.WatValue = QLabel(self.groupBox_7)
        self.WatValue.setObjectName(u"WatValue")
        self.WatValue.setGeometry(QRect(190, 30, 49, 16))
        font2 = QFont()
        font2.setPointSize(12)
        font2.setBold(True)
        self.WatValue.setFont(font2)
        self.BatValue = QLabel(self.groupBox_7)
        self.BatValue.setObjectName(u"BatValue")
        self.BatValue.setGeometry(QRect(190, 60, 49, 16))
        self.BatValue.setFont(font2)
        self.tabWidget.addTab(self.tab_3, "")
        self.groupBox_5.raise_()
        self.checkBox.raise_()
        self.checkBox_2.raise_()
        self.checkBox_3.raise_()
        self.checkBox_4.raise_()
        self.checkBox_5.raise_()
        self.pushButton_4.raise_()
        self.progressBar.raise_()
        self.GrapWidget.raise_()
        self.groupBox_7.raise_()
        self.tab_2 = QWidget()
        self.tab_2.setObjectName(u"tab_2")
        self.tab_2.setEnabled(True)
        self.groupBox = QGroupBox(self.tab_2)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(40, 40, 381, 201))
        self.textEdit = QTextEdit(self.groupBox)
        self.textEdit.setObjectName(u"textEdit")
        self.textEdit.setGeometry(QRect(20, 50, 104, 21))
        self.textEdit_3 = QTextEdit(self.groupBox)
        self.textEdit_3.setObjectName(u"textEdit_3")
        self.textEdit_3.setGeometry(QRect(20, 150, 104, 21))
        self.textEdit_4 = QTextEdit(self.groupBox)
        self.textEdit_4.setObjectName(u"textEdit_4")
        self.textEdit_4.setGeometry(QRect(20, 100, 104, 21))
        self.label_5 = QLabel(self.groupBox)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(140, 50, 111, 16))
        self.label_6 = QLabel(self.groupBox)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(140, 150, 231, 16))
        self.label_8 = QLabel(self.groupBox)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(140, 100, 201, 16))
        self.groupBox_2 = QGroupBox(self.tab_2)
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.groupBox_2.setGeometry(QRect(120, 280, 581, 211))
        self.textEdit_5 = QTextEdit(self.groupBox_2)
        self.textEdit_5.setObjectName(u"textEdit_5")
        self.textEdit_5.setGeometry(QRect(40, 100, 104, 21))
        self.textEdit_8 = QTextEdit(self.groupBox_2)
        self.textEdit_8.setObjectName(u"textEdit_8")
        self.textEdit_8.setGeometry(QRect(40, 50, 104, 21))
        self.textEdit_9 = QTextEdit(self.groupBox_2)
        self.textEdit_9.setObjectName(u"textEdit_9")
        self.textEdit_9.setGeometry(QRect(310, 50, 104, 21))
        self.textEdit_10 = QTextEdit(self.groupBox_2)
        self.textEdit_10.setObjectName(u"textEdit_10")
        self.textEdit_10.setGeometry(QRect(310, 100, 104, 21))
        self.textEdit_11 = QTextEdit(self.groupBox_2)
        self.textEdit_11.setObjectName(u"textEdit_11")
        self.textEdit_11.setGeometry(QRect(310, 150, 104, 21))
        self.textEdit_12 = QTextEdit(self.groupBox_2)
        self.textEdit_12.setObjectName(u"textEdit_12")
        self.textEdit_12.setGeometry(QRect(40, 150, 104, 21))
        self.label_11 = QLabel(self.groupBox_2)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(160, 50, 141, 16))
        self.label_12 = QLabel(self.groupBox_2)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(160, 100, 111, 16))
        self.label_15 = QLabel(self.groupBox_2)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(430, 50, 111, 16))
        self.label_16 = QLabel(self.groupBox_2)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(430, 100, 111, 16))
        self.label_17 = QLabel(self.groupBox_2)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(430, 150, 131, 16))
        self.label_18 = QLabel(self.groupBox_2)
        self.label_18.setObjectName(u"label_18")
        self.label_18.setGeometry(QRect(160, 150, 131, 16))
        self.groupBox_3 = QGroupBox(self.tab_2)
        self.groupBox_3.setObjectName(u"groupBox_3")
        self.groupBox_3.setGeometry(QRect(460, 40, 311, 201))
        self.textEdit_13 = QTextEdit(self.groupBox_3)
        self.textEdit_13.setObjectName(u"textEdit_13")
        self.textEdit_13.setGeometry(QRect(20, 50, 104, 21))
        self.textEdit_14 = QTextEdit(self.groupBox_3)
        self.textEdit_14.setObjectName(u"textEdit_14")
        self.textEdit_14.setGeometry(QRect(20, 100, 104, 21))
        self.label_9 = QLabel(self.groupBox_3)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(140, 100, 161, 16))
        self.label_10 = QLabel(self.groupBox_3)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(140, 50, 141, 16))
        self.textEdit_30 = QTextEdit(self.groupBox_3)
        self.textEdit_30.setObjectName(u"textEdit_30")
        self.textEdit_30.setGeometry(QRect(20, 150, 104, 21))
        self.label_29 = QLabel(self.groupBox_3)
        self.label_29.setObjectName(u"label_29")
        self.label_29.setGeometry(QRect(140, 150, 161, 16))
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_4 = QWidget()
        self.tab_4.setObjectName(u"tab_4")
        self.pushButton_5 = QPushButton(self.tab_4)
        self.pushButton_5.setObjectName(u"pushButton_5")
        self.pushButton_5.setGeometry(QRect(30, 20, 121, 41))
        self.pushButton_5.setFont(font1)
        self.pushButton_5.setAutoFillBackground(True)
        self.progressBar_2 = QProgressBar(self.tab_4)
        self.progressBar_2.setObjectName(u"progressBar_2")
        self.progressBar_2.setGeometry(QRect(180, 30, 591, 23))
        self.progressBar_2.setValue(24)
        self.groupBox_8 = QGroupBox(self.tab_4)
        self.groupBox_8.setObjectName(u"groupBox_8")
        self.groupBox_8.setGeometry(QRect(340, 410, 291, 91))
        font3 = QFont()
        font3.setBold(False)
        self.groupBox_8.setFont(font3)
        self.label_28 = QLabel(self.groupBox_8)
        self.label_28.setObjectName(u"label_28")
        self.label_28.setGeometry(QRect(10, 40, 191, 21))
        font4 = QFont()
        font4.setPointSize(10)
        font4.setBold(False)
        self.label_28.setFont(font4)
        self.WatValue_2 = QLabel(self.groupBox_8)
        self.WatValue_2.setObjectName(u"WatValue_2")
        self.WatValue_2.setGeometry(QRect(220, 40, 49, 16))
        font5 = QFont()
        font5.setPointSize(14)
        font5.setBold(True)
        self.WatValue_2.setFont(font5)
        self.pushButton_12 = QPushButton(self.tab_4)
        self.pushButton_12.setObjectName(u"pushButton_12")
        self.pushButton_12.setGeometry(QRect(30, 430, 121, 41))
        self.pushButton_12.setFont(font1)
        self.pushButton_12.setAutoFillBackground(True)
        self.tabWidget_3 = QTabWidget(self.tab_4)
        self.tabWidget_3.setObjectName(u"tabWidget_3")
        self.tabWidget_3.setGeometry(QRect(30, 70, 731, 321))
        self.tab_5 = QWidget()
        self.tab_5.setObjectName(u"tab_5")
        self.GrapWidget_2 = PlotWidget(self.tab_5)
        self.GrapWidget_2.setObjectName(u"GrapWidget_2")
        self.GrapWidget_2.setGeometry(QRect(0, 0, 541, 291))
        self.pushButton_15 = QPushButton(self.tab_5)
        self.pushButton_15.setObjectName(u"pushButton_15")
        self.pushButton_15.setGeometry(QRect(570, 170, 141, 24))
        self.groupBox_13 = QGroupBox(self.tab_5)
        self.groupBox_13.setObjectName(u"groupBox_13")
        self.groupBox_13.setGeometry(QRect(570, 50, 141, 111))
        self.checkBox_9 = QCheckBox(self.groupBox_13)
        self.checkBox_9.setObjectName(u"checkBox_9")
        self.checkBox_9.setGeometry(QRect(10, 80, 111, 20))
        self.checkBox_8 = QCheckBox(self.groupBox_13)
        self.checkBox_8.setObjectName(u"checkBox_8")
        self.checkBox_8.setGeometry(QRect(10, 60, 131, 20))
        self.checkBox_6 = QCheckBox(self.groupBox_13)
        self.checkBox_6.setObjectName(u"checkBox_6")
        self.checkBox_6.setGeometry(QRect(10, 20, 141, 20))
        self.checkBox_7 = QCheckBox(self.groupBox_13)
        self.checkBox_7.setObjectName(u"checkBox_7")
        self.checkBox_7.setGeometry(QRect(10, 40, 131, 20))
        self.pushButton_17 = QPushButton(self.tab_5)
        self.pushButton_17.setObjectName(u"pushButton_17")
        self.pushButton_17.setGeometry(QRect(570, 200, 141, 24))
        self.tabWidget_3.addTab(self.tab_5, "")
        self.tab_8 = QWidget()
        self.tab_8.setObjectName(u"tab_8")
        self.GrapWidget_3 = QWidget(self.tab_8)
        self.GrapWidget_3.setObjectName(u"GrapWidget_3")
        self.GrapWidget_3.setGeometry(QRect(200, 0, 521, 291))
        self.groupBox_9 = QGroupBox(self.tab_8)
        self.groupBox_9.setObjectName(u"groupBox_9")
        self.groupBox_9.setGeometry(QRect(10, 100, 171, 91))
        self.label_30 = QLabel(self.groupBox_9)
        self.label_30.setObjectName(u"label_30")
        self.label_30.setGeometry(QRect(10, 30, 191, 16))
        self.label_31 = QLabel(self.groupBox_9)
        self.label_31.setObjectName(u"label_31")
        self.label_31.setGeometry(QRect(10, 60, 191, 16))
        self.WatValue_3 = QLabel(self.groupBox_9)
        self.WatValue_3.setObjectName(u"WatValue_3")
        self.WatValue_3.setGeometry(QRect(130, 30, 49, 16))
        self.WatValue_3.setFont(font2)
        self.BatValue_3 = QLabel(self.groupBox_9)
        self.BatValue_3.setObjectName(u"BatValue_3")
        self.BatValue_3.setGeometry(QRect(130, 60, 49, 16))
        self.BatValue_3.setFont(font2)
        self.pushButton_16 = QPushButton(self.tab_8)
        self.pushButton_16.setObjectName(u"pushButton_16")
        self.pushButton_16.setGeometry(QRect(10, 200, 171, 24))
        self.tabWidget_3.addTab(self.tab_8, "")
        self.tabWidget.addTab(self.tab_4, "")
        self.Parameters = QWidget()
        self.Parameters.setObjectName(u"Parameters")
        self.pushButton_13 = QPushButton(self.Parameters)
        self.pushButton_13.setObjectName(u"pushButton_13")
        self.pushButton_13.setGeometry(QRect(320, 480, 75, 24))
        self.pushButton_14 = QPushButton(self.Parameters)
        self.pushButton_14.setObjectName(u"pushButton_14")
        self.pushButton_14.setGeometry(QRect(400, 480, 91, 24))
        self.groupBox_10 = QGroupBox(self.Parameters)
        self.groupBox_10.setObjectName(u"groupBox_10")
        self.groupBox_10.setGeometry(QRect(20, 20, 461, 331))
        self.label_32 = QLabel(self.groupBox_10)
        self.label_32.setObjectName(u"label_32")
        self.label_32.setGeometry(QRect(10, 90, 341, 16))
        self.textEdit_19 = QTextEdit(self.groupBox_10)
        self.textEdit_19.setObjectName(u"textEdit_19")
        self.textEdit_19.setGeometry(QRect(350, 170, 104, 21))
        self.label_33 = QLabel(self.groupBox_10)
        self.label_33.setObjectName(u"label_33")
        self.label_33.setGeometry(QRect(10, 130, 311, 16))
        self.label_34 = QLabel(self.groupBox_10)
        self.label_34.setObjectName(u"label_34")
        self.label_34.setGeometry(QRect(10, 170, 301, 16))
        self.textEdit_20 = QTextEdit(self.groupBox_10)
        self.textEdit_20.setObjectName(u"textEdit_20")
        self.textEdit_20.setGeometry(QRect(350, 130, 104, 21))
        self.label_35 = QLabel(self.groupBox_10)
        self.label_35.setObjectName(u"label_35")
        self.label_35.setGeometry(QRect(10, 210, 441, 16))
        self.textEdit_21 = QTextEdit(self.groupBox_10)
        self.textEdit_21.setObjectName(u"textEdit_21")
        self.textEdit_21.setGeometry(QRect(350, 250, 104, 21))
        self.label_36 = QLabel(self.groupBox_10)
        self.label_36.setObjectName(u"label_36")
        self.label_36.setGeometry(QRect(10, 250, 181, 16))
        self.label_37 = QLabel(self.groupBox_10)
        self.label_37.setObjectName(u"label_37")
        self.label_37.setGeometry(QRect(10, 40, 441, 16))
        self.textEdit_18 = QTextEdit(self.groupBox_10)
        self.textEdit_18.setObjectName(u"textEdit_18")
        self.textEdit_18.setGeometry(QRect(350, 90, 104, 21))
        self.textEdit_23 = QTextEdit(self.groupBox_10)
        self.textEdit_23.setObjectName(u"textEdit_23")
        self.textEdit_23.setGeometry(QRect(350, 210, 104, 21))
        self.label_42 = QLabel(self.groupBox_10)
        self.label_42.setObjectName(u"label_42")
        self.label_42.setGeometry(QRect(10, 290, 181, 16))
        self.textEdit_25 = QTextEdit(self.groupBox_10)
        self.textEdit_25.setObjectName(u"textEdit_25")
        self.textEdit_25.setGeometry(QRect(350, 290, 104, 21))
        self.groupBox_11 = QGroupBox(self.Parameters)
        self.groupBox_11.setObjectName(u"groupBox_11")
        self.groupBox_11.setGeometry(QRect(500, 70, 271, 251))
        self.label_38 = QLabel(self.groupBox_11)
        self.label_38.setObjectName(u"label_38")
        self.label_38.setGeometry(QRect(10, 40, 341, 16))
        self.label_39 = QLabel(self.groupBox_11)
        self.label_39.setObjectName(u"label_39")
        self.label_39.setGeometry(QRect(10, 60, 341, 16))
        self.label_40 = QLabel(self.groupBox_11)
        self.label_40.setObjectName(u"label_40")
        self.label_40.setGeometry(QRect(20, 100, 181, 16))
        self.label_41 = QLabel(self.groupBox_11)
        self.label_41.setObjectName(u"label_41")
        self.label_41.setGeometry(QRect(20, 170, 211, 16))
        self.textEdit_22 = QTextEdit(self.groupBox_11)
        self.textEdit_22.setObjectName(u"textEdit_22")
        self.textEdit_22.setGeometry(QRect(50, 130, 104, 21))
        self.label_43 = QLabel(self.groupBox_11)
        self.label_43.setObjectName(u"label_43")
        self.label_43.setGeometry(QRect(160, 130, 181, 16))
        self.textEdit_24 = QTextEdit(self.groupBox_11)
        self.textEdit_24.setObjectName(u"textEdit_24")
        self.textEdit_24.setGeometry(QRect(50, 200, 104, 21))
        self.label_44 = QLabel(self.groupBox_11)
        self.label_44.setObjectName(u"label_44")
        self.label_44.setGeometry(QRect(160, 200, 181, 16))
        self.groupBox_12 = QGroupBox(self.Parameters)
        self.groupBox_12.setObjectName(u"groupBox_12")
        self.groupBox_12.setGeometry(QRect(20, 359, 751, 101))
        self.label_45 = QLabel(self.groupBox_12)
        self.label_45.setObjectName(u"label_45")
        self.label_45.setGeometry(QRect(10, 30, 341, 16))
        self.label_46 = QLabel(self.groupBox_12)
        self.label_46.setObjectName(u"label_46")
        self.label_46.setGeometry(QRect(10, 70, 341, 16))
        self.label_47 = QLabel(self.groupBox_12)
        self.label_47.setObjectName(u"label_47")
        self.label_47.setGeometry(QRect(430, 30, 341, 16))
        self.label_48 = QLabel(self.groupBox_12)
        self.label_48.setObjectName(u"label_48")
        self.label_48.setGeometry(QRect(430, 70, 341, 16))
        self.textEdit_26 = QTextEdit(self.groupBox_12)
        self.textEdit_26.setObjectName(u"textEdit_26")
        self.textEdit_26.setGeometry(QRect(190, 30, 104, 21))
        self.textEdit_27 = QTextEdit(self.groupBox_12)
        self.textEdit_27.setObjectName(u"textEdit_27")
        self.textEdit_27.setGeometry(QRect(190, 70, 104, 21))
        self.textEdit_28 = QTextEdit(self.groupBox_12)
        self.textEdit_28.setObjectName(u"textEdit_28")
        self.textEdit_28.setGeometry(QRect(570, 70, 104, 21))
        self.textEdit_29 = QTextEdit(self.groupBox_12)
        self.textEdit_29.setObjectName(u"textEdit_29")
        self.textEdit_29.setGeometry(QRect(570, 30, 104, 21))
        self.label_49 = QLabel(self.groupBox_12)
        self.label_49.setObjectName(u"label_49")
        self.label_49.setGeometry(QRect(300, 30, 181, 16))
        self.label_50 = QLabel(self.groupBox_12)
        self.label_50.setObjectName(u"label_50")
        self.label_50.setGeometry(QRect(300, 70, 181, 16))
        self.label_51 = QLabel(self.groupBox_12)
        self.label_51.setObjectName(u"label_51")
        self.label_51.setGeometry(QRect(680, 70, 181, 16))
        self.label_52 = QLabel(self.groupBox_12)
        self.label_52.setObjectName(u"label_52")
        self.label_52.setGeometry(QRect(680, 30, 181, 16))
        self.tabWidget.addTab(self.Parameters, "")
        self.groupBox_10.raise_()
        self.pushButton_13.raise_()
        self.pushButton_14.raise_()
        self.groupBox_11.raise_()
        self.groupBox_12.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 791, 33))
        self.menuSolarOptimus_Tool = QMenu(self.menubar)
        self.menuSolarOptimus_Tool.setObjectName(u"menuSolarOptimus_Tool")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.menubar.addAction(self.menuSolarOptimus_Tool.menuAction())

        self.retranslateUi(MainWindow)

        self.tabWidget.setCurrentIndex(2)
        self.tabWidget_2.setCurrentIndex(0)
        self.tabWidget_3.setCurrentIndex(1)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        ___qtablewidgetitem = self.tableWidget.horizontalHeaderItem(0)
        ___qtablewidgetitem.setText(QCoreApplication.translate("MainWindow", u"Load Name", None));
        ___qtablewidgetitem1 = self.tableWidget.horizontalHeaderItem(1)
        ___qtablewidgetitem1.setText(QCoreApplication.translate("MainWindow", u"Power [W]", None));
        ___qtablewidgetitem2 = self.tableWidget.horizontalHeaderItem(2)
        ___qtablewidgetitem2.setText(QCoreApplication.translate("MainWindow", u"Time of Usage [h]", None));
        ___qtablewidgetitem3 = self.tableWidget.horizontalHeaderItem(3)
        ___qtablewidgetitem3.setText(QCoreApplication.translate("MainWindow", u"From [xx:xx XM]", None));
        ___qtablewidgetitem4 = self.tableWidget.horizontalHeaderItem(4)
        ___qtablewidgetitem4.setText(QCoreApplication.translate("MainWindow", u"To [xx:xx XM]", None));
        self.pushButton_2.setText(QCoreApplication.translate("MainWindow", u"Add Load", None))
        self.pushButton_3.setText(QCoreApplication.translate("MainWindow", u"Remove Load", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"Enter a sample day load profile depending on the seaon", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_6), QCoreApplication.translate("MainWindow", u"Winter", None))
        ___qtablewidgetitem5 = self.tableWidget_3.horizontalHeaderItem(0)
        ___qtablewidgetitem5.setText(QCoreApplication.translate("MainWindow", u"Load Name", None));
        ___qtablewidgetitem6 = self.tableWidget_3.horizontalHeaderItem(1)
        ___qtablewidgetitem6.setText(QCoreApplication.translate("MainWindow", u"Power [W]", None));
        ___qtablewidgetitem7 = self.tableWidget_3.horizontalHeaderItem(2)
        ___qtablewidgetitem7.setText(QCoreApplication.translate("MainWindow", u"Time of Usage [h]", None));
        ___qtablewidgetitem8 = self.tableWidget_3.horizontalHeaderItem(3)
        ___qtablewidgetitem8.setText(QCoreApplication.translate("MainWindow", u"From [xx:xx XM]", None));
        ___qtablewidgetitem9 = self.tableWidget_3.horizontalHeaderItem(4)
        ___qtablewidgetitem9.setText(QCoreApplication.translate("MainWindow", u"To [xx:xx XM]", None));
        self.pushButton_7.setText(QCoreApplication.translate("MainWindow", u"Add Load", None))
        self.pushButton_6.setText(QCoreApplication.translate("MainWindow", u"Remove Load", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"Enter a sample day load profile depending on the seaon", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_7), QCoreApplication.translate("MainWindow", u"Spring", None))
        ___qtablewidgetitem10 = self.tableWidget_4.horizontalHeaderItem(0)
        ___qtablewidgetitem10.setText(QCoreApplication.translate("MainWindow", u"Load Name", None));
        ___qtablewidgetitem11 = self.tableWidget_4.horizontalHeaderItem(1)
        ___qtablewidgetitem11.setText(QCoreApplication.translate("MainWindow", u"Power [W]", None));
        ___qtablewidgetitem12 = self.tableWidget_4.horizontalHeaderItem(2)
        ___qtablewidgetitem12.setText(QCoreApplication.translate("MainWindow", u"Time of Usage [h]", None));
        ___qtablewidgetitem13 = self.tableWidget_4.horizontalHeaderItem(3)
        ___qtablewidgetitem13.setText(QCoreApplication.translate("MainWindow", u"From [xx:xx XM]", None));
        ___qtablewidgetitem14 = self.tableWidget_4.horizontalHeaderItem(4)
        ___qtablewidgetitem14.setText(QCoreApplication.translate("MainWindow", u"To [xx:xx XM]", None));
        self.pushButton_8.setText(QCoreApplication.translate("MainWindow", u"Remove Load", None))
        self.pushButton_9.setText(QCoreApplication.translate("MainWindow", u"Add Load", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"Enter a sample day load profile depending on the seaon", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.Mansoon), QCoreApplication.translate("MainWindow", u"Mansoon", None))
        ___qtablewidgetitem15 = self.tableWidget_5.horizontalHeaderItem(0)
        ___qtablewidgetitem15.setText(QCoreApplication.translate("MainWindow", u"Load Name", None));
        ___qtablewidgetitem16 = self.tableWidget_5.horizontalHeaderItem(1)
        ___qtablewidgetitem16.setText(QCoreApplication.translate("MainWindow", u"Power [W]", None));
        ___qtablewidgetitem17 = self.tableWidget_5.horizontalHeaderItem(2)
        ___qtablewidgetitem17.setText(QCoreApplication.translate("MainWindow", u"Time of Usage [h]", None));
        ___qtablewidgetitem18 = self.tableWidget_5.horizontalHeaderItem(3)
        ___qtablewidgetitem18.setText(QCoreApplication.translate("MainWindow", u"From [xx:xx XM]", None));
        ___qtablewidgetitem19 = self.tableWidget_5.horizontalHeaderItem(4)
        ___qtablewidgetitem19.setText(QCoreApplication.translate("MainWindow", u"To [xx:xx XM]", None));
        self.pushButton_11.setText(QCoreApplication.translate("MainWindow", u"Add Load", None))
        self.pushButton_10.setText(QCoreApplication.translate("MainWindow", u"Remove Load", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"Enter a sample day load profile depending on the seaon", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_10), QCoreApplication.translate("MainWindow", u"Summer", None))
        self.pushButton.setText(QCoreApplication.translate("MainWindow", u"Copy Sample to other seasons", None))
        self.groupBox_4.setTitle(QCoreApplication.translate("MainWindow", u"System Info", None))
        self.label_19.setText(QCoreApplication.translate("MainWindow", u"System Longitude", None))
        self.label_20.setText(QCoreApplication.translate("MainWindow", u"System Latitude", None))
        self.label_21.setText(QCoreApplication.translate("MainWindow", u"Designed Years", None))
        self.pushButton_18.setText(QCoreApplication.translate("MainWindow", u"Browse Files", None))
        self.label_53.setText(QCoreApplication.translate("MainWindow", u"OPTIONAL: Add your solar data file in .csv form. Verify csv compatibility in user manual !", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QCoreApplication.translate("MainWindow", u"1 - Load Profile", None))
        self.checkBox.setText(QCoreApplication.translate("MainWindow", u"Critical (0%-1% ENSP)", None))
        self.checkBox_2.setText(QCoreApplication.translate("MainWindow", u"High (1%-4% ENSP)", None))
        self.checkBox_3.setText(QCoreApplication.translate("MainWindow", u"Medium (4%-6% ENSP)", None))
        self.checkBox_4.setText(QCoreApplication.translate("MainWindow", u"Basic (6%-10% ENSP)", None))
        self.checkBox_5.setText(QCoreApplication.translate("MainWindow", u"Minimal (>10% ENSP", None))
        self.groupBox_5.setTitle(QCoreApplication.translate("MainWindow", u"Robustness selector", None))
        self.label_22.setText(QCoreApplication.translate("MainWindow", u"How important is energy availability?", None))
        self.label_23.setText(QCoreApplication.translate("MainWindow", u"Choose one option at the end of the sim.", None))
        self.groupBox_6.setTitle(QCoreApplication.translate("MainWindow", u"Focus of the Optimization", None))
        self.label_24.setText(QCoreApplication.translate("MainWindow", u"Choose a single focus for the optimization. ", None))
        self.label_25.setText(QCoreApplication.translate("MainWindow", u"It will affect significantly the ouput of the tool", None))
        self.pushButton_4.setText(QCoreApplication.translate("MainWindow", u"Launch Tool", None))
        self.groupBox_7.setTitle(QCoreApplication.translate("MainWindow", u"Optimized Value", None))
        self.label_26.setText(QCoreApplication.translate("MainWindow", u"Peak Solar Panel Wattage [W]:", None))
        self.label_27.setText(QCoreApplication.translate("MainWindow", u"Battery Capacity [Wh]:", None))
        self.WatValue.setText(QCoreApplication.translate("MainWindow", u"45", None))
        self.BatValue.setText(QCoreApplication.translate("MainWindow", u"45", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QCoreApplication.translate("MainWindow", u"2 - First Optimization", None))
        self.groupBox.setTitle(QCoreApplication.translate("MainWindow", u"Solar Panel", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"Peak Power [W]", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"Power Temperature Coefficient [%/\u00b0C]", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"Total Number of Panels", None))
        self.groupBox_2.setTitle(QCoreApplication.translate("MainWindow", u"Battery Array", None))
        self.label_11.setText(QCoreApplication.translate("MainWindow", u"Nominal Capacity [Ah]", None))
        self.label_12.setText(QCoreApplication.translate("MainWindow", u"Minimum SOC [%]", None))
        self.label_15.setText(QCoreApplication.translate("MainWindow", u"Cycle Life", None))
        self.label_16.setText(QCoreApplication.translate("MainWindow", u"Lifetime in Years", None))
        self.label_17.setText(QCoreApplication.translate("MainWindow", u"Battery Strings in Parallel", None))
        self.label_18.setText(QCoreApplication.translate("MainWindow", u"Battery Strings in Series", None))
        self.groupBox_3.setTitle(QCoreApplication.translate("MainWindow", u"PCU", None))
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"Charge Control Efficiency [%]", None))
        self.label_10.setText(QCoreApplication.translate("MainWindow", u"Inverter Efficiency [%]", None))
        self.label_29.setText(QCoreApplication.translate("MainWindow", u"Max Charge Current [A]", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QCoreApplication.translate("MainWindow", u"3 - System parameters", None))
        self.pushButton_5.setText(QCoreApplication.translate("MainWindow", u"Launch Tool", None))
        self.groupBox_8.setTitle(QCoreApplication.translate("MainWindow", u"Precise value of ENS/LOL - Percentage", None))
        self.label_28.setText(QCoreApplication.translate("MainWindow", u"Energy Not Supplied (ENS) [%]:", None))
        self.WatValue_2.setText(QCoreApplication.translate("MainWindow", u"10", None))
        self.pushButton_12.setText(QCoreApplication.translate("MainWindow", u"Download raw data", None))
        self.pushButton_15.setText(QCoreApplication.translate("MainWindow", u"Sample New Day", None))
        self.groupBox_13.setTitle(QCoreApplication.translate("MainWindow", u"Parameters to plot:", None))
        self.checkBox_9.setText(QCoreApplication.translate("MainWindow", u"Battery SOC [%]", None))
        self.checkBox_8.setText(QCoreApplication.translate("MainWindow", u"Load Demand [W]", None))
        self.checkBox_6.setText(QCoreApplication.translate("MainWindow", u"Panel Power [W]", None))
        self.checkBox_7.setText(QCoreApplication.translate("MainWindow", u"Battery Power [W]", None))
        self.pushButton_17.setText(QCoreApplication.translate("MainWindow", u"Clear Oldest Trace", None))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_5), QCoreApplication.translate("MainWindow", u"Sample Day", None))
        self.groupBox_9.setTitle(QCoreApplication.translate("MainWindow", u"Battery Analysis", None))
        self.label_30.setText(QCoreApplication.translate("MainWindow", u"Lifetime in years:", None))
        self.label_31.setText(QCoreApplication.translate("MainWindow", u"Final Capacity", None))
        self.WatValue_3.setText(QCoreApplication.translate("MainWindow", u"10", None))
        self.BatValue_3.setText(QCoreApplication.translate("MainWindow", u"3", None))
        self.pushButton_16.setText(QCoreApplication.translate("MainWindow", u"Clear Oldest Trace", None))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_8), QCoreApplication.translate("MainWindow", u"Battery Analysis", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), QCoreApplication.translate("MainWindow", u"4 - Verification", None))
        self.pushButton_13.setText(QCoreApplication.translate("MainWindow", u"Save", None))
        self.pushButton_14.setText(QCoreApplication.translate("MainWindow", u"Restore Default", None))
        self.groupBox_10.setTitle(QCoreApplication.translate("MainWindow", u"PV-Modeling", None))
        self.label_32.setText(QCoreApplication.translate("MainWindow", u"Losses due to shading by surrounding houses or trees...", None))
        self.label_33.setText(QCoreApplication.translate("MainWindow", u"Loss due to mismatch between modules of the PV-array. ", None))
        self.label_34.setText(QCoreApplication.translate("MainWindow", u"Loss of energy due to the connectors in the system.", None))
        self.label_35.setText(QCoreApplication.translate("MainWindow", u"Nameplate rating. Losses due to field variation from datasheet.", None))
        self.label_36.setText(QCoreApplication.translate("MainWindow", u"Light-induced degradation.", None))
        self.label_37.setText(QCoreApplication.translate("MainWindow", u"Modify the constant efficiency of the solar panel. Please refer to PVWatt's loss tool.", None))
        self.label_42.setText(QCoreApplication.translate("MainWindow", u"Losses in a section of cable.", None))
        self.groupBox_11.setTitle(QCoreApplication.translate("MainWindow", u"Soiling-Modeling", None))
        self.label_38.setText(QCoreApplication.translate("MainWindow", u"Modify the parameters of the soiling model. ", None))
        self.label_39.setText(QCoreApplication.translate("MainWindow", u"Refer to PVLib's documentation.", None))
        self.label_40.setText(QCoreApplication.translate("MainWindow", u"Rate at which PV is cleaned:", None))
        self.label_41.setText(QCoreApplication.translate("MainWindow", u"Amount of rain need to clean the PV:", None))
        self.label_43.setText(QCoreApplication.translate("MainWindow", u"[Weeks]", None))
        self.label_44.setText(QCoreApplication.translate("MainWindow", u"[mm]", None))
        self.groupBox_12.setTitle(QCoreApplication.translate("MainWindow", u"Other", None))
        self.label_45.setText(QCoreApplication.translate("MainWindow", u"Mean price per W of solar panel", None))
        self.label_46.setText(QCoreApplication.translate("MainWindow", u"Mean price per Wh of battery", None))
        self.label_47.setText(QCoreApplication.translate("MainWindow", u"Load efficiency:", None))
        self.label_48.setText(QCoreApplication.translate("MainWindow", u"Initial state of charge:", None))
        self.label_49.setText(QCoreApplication.translate("MainWindow", u"[INR]", None))
        self.label_50.setText(QCoreApplication.translate("MainWindow", u"[INR]", None))
        self.label_51.setText(QCoreApplication.translate("MainWindow", u"[%]", None))
        self.label_52.setText(QCoreApplication.translate("MainWindow", u"[%]", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Parameters), QCoreApplication.translate("MainWindow", u"Parameters", None))
        self.menuSolarOptimus_Tool.setTitle(QCoreApplication.translate("MainWindow", u"SolarOptimus Tool ", None))
    # retranslateUi

